### ISSUE TITLE
It doesn't work because of the wrong number of arguments of `save()` method

### ISSUE THREAD

**Issue by meteorlin** [debanjandhar12/Obsidian-Anki-Sync#1]
![image](https://user-images.githubusercontent.com/49402403/131947815-6f42324f-81e2-445c-8c09-e3e1f83445da.png)

**Comment by debanjandhar12** [comment]
Sorry but i failed to reproduce the issue on my end.

Can you give me some more information? Specifically:
1. Obsidian Version: 
1. Screenshot of Developer Console (Click `Ctrl + Shift + I' and then try to run the script and screenshot it):

**Comment by meteorlin** [comment]
My Obsidian Version is 0.12.15, and here is the console screenshot:
![image](https://user-images.githubusercontent.com/49402403/131976226-67d9137b-cf21-41e6-bb26-281b47a0c796.png)

**Comment by jenshda** [comment]
I have the same problem exactly with the latest Obsidian version. I get the same error message both with the toggles on and off and after restarting both apps. 

<img width="309" alt="Screenshot 2021-09-29 at 22 09 39" src="https://user-images.githubusercontent.com/83638075/135341718-7353eea1-cdea-4542-a5b0-6708639268ec.png">

**Comment by debanjandhar12** [comment]
> I have the same problem exactly with the latest Obsidian version. I get the same error message both with the toggles on and off and after restarting both apps.
> 
> <img alt="Screenshot 2021-09-29 at 22 09 39" width="309" src="https://user-images.githubusercontent.com/83638075/135341718-7353eea1-cdea-4542-a5b0-6708639268ec.png">

Sorry, I am still failing to reproduce the issue on my end.

Can you give me some more information? Specifically:

1. Operating System (with version):
1. Anki Version:
2. AnkiConnect Version:
1.  Screenshot of Developer Console (Click `Ctrl + Shift + I' and then try to run the script and screenshot it):

**Comment by tyr13** [comment]
I have this issue as well. 
- Windows 10
- Anki Version ⁨2.1.48 (fb07bad3)⁩
- Obsidian v0.12.15
- I checked the console and all network response are OK (200).

**Comment by jenshda** [comment]
1. Operating System (with version): Mac OS 11.6
 2. Anki Version: ⁨2.1.46
 3. AnkiConnect Version: The one from September
 4. Screenshot of Developer Console (Click `Ctrl + Shift + I' and then try to run the script and screenshot it): See attachment

Wishing you a great rest of your day!

Kind regards,
Jens Halford Dyster-Aas
