### ISSUE TITLE
The uploaded image directory is not located in the correct path

### ISSUE THREAD

**Issue by wujun001** [debanjandhar12/Obsidian-Anki-Sync#10]
`![](Wtf_SH,graph流程图箭头.jpg)`

correct path：
C:\JGY\Obsidian\md\P\mermaid给你的文档加层滤镜\Wtf_SH,graph流程图箭头.jpg.jpg

bug log
![image](https://user-images.githubusercontent.com/29793989/141682407-24ee3688-f403-4df2-a688-35ebf8993421.png)

It was normal before, but error after update.

other problems
Images in ANki are not updated after OB images are updated

**Comment by debanjandhar12** [comment]
> other problems Images in ANki are not updated after OB images are updated

The image should update after syncing again. If it doesn't, please mention your OS with version, Obsidian Version, Anki Version and AnkiConnect Version.
