### ISSUE TITLE
Put picture(s) in "Extra" column

### ISSUE THREAD

**Issue by azrilamil** [debanjandhar12/Obsidian-Anki-Sync#11]
Hi, is there any way to put the picture directly to the "Extra" column in Anki?
Currently it is under the "Text" column. 
If I change it in Anki, it'll switch back to the "Text" column when I resynch. 
I only need the picture on the Back of the card for review purposes.

![image](https://user-images.githubusercontent.com/78202998/143204523-2cbeb852-ad2c-47b6-a930-bf1f4c3ed9db.png)

![image](https://user-images.githubusercontent.com/78202998/143204672-50fd7ab3-495a-4307-99ad-1beba58444b1.png)

I want it like this
![image](https://user-images.githubusercontent.com/78202998/143204799-2be245cf-08b0-4eed-94de-5b4772a88e75.png)

**Comment by debanjandhar12** [comment]
Not at the moment,

I will look into supporting the use-case by treating the extra string as markdown in the next version.

**Comment by azrilamil** [comment]
Looking forward for the next updates! thanks

**Comment by debanjandhar12** [comment]
This has been implemented and will be released with the next version next week.

You can use this code for achieving the use-case:
```<!-- clozeblock-start extra="![Triangle](https://i.imgur.com/MS0893z.png)" -->
cloze contents....
<!-- clozeblock-end -->```
