### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by zhaohui0923** [debanjandhar12/Obsidian-Anki-Sync#13]
Could you please implement this feature: use the obsidian's native hilight syntax to make the cloze?

```
<!-- clozeblock-start -->
This is the ==use case==, in this way, users can be ==less== distracted
<!-- clozeblock-end -->
```

Make it the same semantics as

```
<!-- clozeblock-start -->
This is the {{c1::use case}}, in this way, users can be {{c2::less}} distracted
<!-- clozeblock-end -->
```

**Advantage**:
- Less type to make the cloze
- Less distracted in preview mode

**Disadvantage**
- Less control on whether some cloze should appear at the same time
- More development effort

Thanks for this great plugin, Look forward to your reply :)

**Comment by debanjandhar12** [comment]
This has been implemented and will be released with the next version next week.
