### ISSUE TITLE
Error: 'NoneType' object has no attribute 'write'

### ISSUE THREAD

**Issue by vvh-1** [debanjandhar12/Obsidian-Anki-Sync#16]
![image](https://user-images.githubusercontent.com/59473428/159445335-9f5050b8-1c32-4a3b-9aa1-48296b321c5d.png)

I had installed obsidian_to_anki, flashicard and this plugin but had the same problem.
I think I installed Ankiconnect in the right way. Is it possible that there might be some port occupancy issues on my computer? 
looking forward to your help~

**Comment by debanjandhar12** [comment]
Which anki and ankiconnect version are you on?

Also what OS?

**Comment by vvh-1** [comment]
The debug information from Anki for 64bit windows is copied as follows:

    Anki 2.1.50 (43c41d76) Python 3.9.7 Qt 5.15.2 PyQt 5.15.5
    Platform: Windows 10
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2022-03-22 12:22:36
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    AnkiConnect ['2055492159', 2022-02-20T03:11, 'None', mod]
    
    ===IDs of active AnkiWeb add-ons===
    2055492159
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by debanjandhar12** [comment]
Yep, like I thought. AnkiConnect doesn't support Anki 2.1.50 yet. https://github.com/FooSoft/anki-connect/issues/308

Switching back to Anki 2.1.49 should solve this.
