### ISSUE TITLE
Instruction unlear: Replace Code inside AnkiConnect or paste it under the standard code? 

### ISSUE THREAD

**Issue by rorar** [debanjandhar12/Obsidian-Anki-Sync#6]
Should it be like this:
![image](https://user-images.githubusercontent.com/44790144/137199802-88183e41-24df-4439-a730-7654b8ec5d6e.png)
or do [you want it that way (tell my why?)](https://youtu.be/4fndeDfaWCg?t=88)
![image](https://user-images.githubusercontent.com/44790144/137200229-651c120f-d15e-43c5-82c2-6bc9c9e1746e.png)

**Comment by debanjandhar12** [comment]
Documentation has been updated with an alternative easier way of installation.
