### ISSUE TITLE
Specifying card tags in attributes?

### ISSUE THREAD

**Issue by yett1873** [debanjandhar12/Obsidian-Anki-Sync#9]
> Many other features like extra field, tags etc...

Would you please illustrate how to tags to a card in the doc?

**Comment by debanjandhar12** [comment]
Tags can be specified at the top of the page as yaml properties in obsidian.

```
---
tags: math
---
```

or 

```
---
tags: [untilted, mathe]
---
```

**Comment by yett1873** [comment]
That is really helpful, thanks a lot!
